name: TESTIN Running Loop Workflow

on:
  push:
    branches:
      - devops/*

# concurrency:
#   group: ${{ github.workflow }}_environment
#   cancel-in-progress: false  
    

env:
  # REF_INPUT: ${{ github.event.inputs.ref_name }}
  REF_INPUT: ${{ github.ref_name }}

jobs:
  testin-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Original Data
        run: echo "DEVELOPMENT!!"

      - name: Current branch
        run: echo "Hello am on ${{ env.REF_INPUT }} branch!!"
        
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF_INPUT }}

   
