name: TESTIN Running Loop Workflow

on:
  push:
    branches:
      - devops/*

jobs:
  long_loop:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.event.inputs.environment }}-environment
      cancel-in-progress: true  # Cancel any in-progress jobs for the same environment

    steps:
      - name: Start Long Loop
        run: |
          echo "Starting long loop..."

          # Define the loop to run for a long time
          for i in {1..10000}; do
            echo "Loop iteration $i"

            # Sleep for 30 seconds between iterations to extend runtime
            sleep 30

            # Check if it's time to break the loop early (optional)
            if [ $i -eq 5000 ]; then
              echo "Reached halfway, continuing..."
            fi
          done

          echo "Long loop completed."
