name: Simple Workflow

on:
  push:
    branches:
      - devops/*

# on:
#   workflow_dispatch:
#     inputs:
#       ref_name:
#         type: choice
#         description: "Select branchname !"
#         required: true
#         options: 
#         - devops/dev
#         - devops/prod
#         - devops/staging

    # concurrency:
    #   group: ${{ github.ref }}-environment
      # cancel-in-progress: false  # Cancel any in-progress jobs for the same environment

env:
  # REF_INPUT: ${{ github.event.inputs.ref_name }}
  REF_INPUT: ${{ github.ref_name }}

jobs:
  testin-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Original Data
        run: echo "DEVELOPMENT!!"

      - name: Sleep
        run: sleep 10

      - name: Current branch
        run: echo "Hello am on ${{ env.REF_INPUT }} branch!!"
        
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF_INPUT }}