name: Wor_Dispatch_Input_Branch

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: "Select branchname !"
        required: true
        options: 
        - devops/dev
        - devops/prod
        - devops/staging

jobs:
  testin-flow:
    runs-on: ubuntu-latest

    steps:
      - name: 
        run: echo "DEVELOPMENT!!"

      - name: Current branch
        run: echo "Hello am on ${{ github.event.inputs.name }} branch!!"
        
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.name }}