name: Wor_Dispatch_Input_Branch

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: "Add branchname for deployment"
        required: true
        options: 
        - develop
        - production
        - staging

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello am on ${{ github.event.inputs.name }} branch!!"





# name: Solar System Workflow

# on: 
#   push:
#     branches:
#       - main
#       - 'feature/*'

# on:
#   workflow_dispatch:
#     inputs:
#       name:
#        description: "Required add env deployment!!"
#        required: true
#        default: 'development'
#        type: choice
#        options: 
#        - development
#        - staging
#        - production

# jobs:
#   init:
#     name: Build and Deploy
#     runs-on: ubuntu-20.04
#     steps:
#       - run: echo "This is branch ${{ github.event.inputs.name }} !!"
#       - name: Checkout
#         uses: actions/checkout@v2